---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nekko-cloud-ingress
  labels:
    app: nekko-cloud
spec:
  ingressClassName: cloudflare-tunnel
  rules:
    - host: 'nc.nekko-lab.dev'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-nc
                port:
                  number: 80
